version: '3.2' #docker-compose.yml
services:
  jenkins:
    restart: always
    build:
      context: jenkins/
    privileged: false
    user: jenkins
    ports:
      - 80:8080
      - 50005:50000
    container_name: jenkins
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 30.0.0.0/24
    # volumes:
    #   - ./jenkins/jenkins_home:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock